name: CI Pipeline  

on:  
  push:  
    branches: [ main ]  
  pull_request:  
    branches: [ main ]  

jobs:  
  build:  
    runs-on: ubuntu-latest  

    steps:  
      - name: Checkout code  
        uses: actions/checkout@v2  

      - name: Setup .NET Core  
        uses: actions/setup-dotnet@v1  
        with:  
          dotnet-version: '5.0.x'  

      - name: Restore dependencies  
        run: dotnet restore  MyApp/MyApp.csproj

      - name: Build  
        run: dotnet build MyApp/MyApp.csproj --no-restore  

      - name: Run tests  
        run: dotnet test MyApp/MyApp.csproj --no-build --verbosity normal  

      - name: Run DeepSource analysis  
        run: docker run --rm -v $(pwd):/workspace deepsourceio/analyzer run --analyzer csharp  
